
CREATE TABLE user (
  id INTEGER IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  phoneNo  VARCHAR(100),
  email  VARCHAR(255)
);
CREATE TABLE BOOKS (
  id INTEGER IDENTITY PRIMARY KEY,
  title VARCHAR(255),
  author  VARCHAR(255),
  isbn  VARCHAR(100)
);

CREATE TABLE USER_BOOKS (
  USER_ID INTEGER,
  BOOKS_ID INTEGER
);
