--DROP TABLE users IF EXISTS;

CREATE TABLE user (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255),
  phoneNo  VARCHAR(30),
  email  VARCHAR(100),
);
CREATE TABLE BOOKS (
  id INTEGER PRIMARY KEY,
  title VARCHAR(255),
  author  VARCHAR(255),
  isbn  VARCHAR(100),
);

CREATE TABLE USER_BOOKS (
  USER_ID INTEGER FOREIGN KEY REFERENCES USER(ID),
  BOOKS_ID INTEGER FOREIGN KEY REFERENCES BOOKS(ID),
);
